### ISSUE TITLE
Drag'n'Drop does not work in Firefox

### ISSUE THREAD

**Issue by Fensterbank** [tobihagemann/shitishot#7]
The drag'n'drop feature seems to be broken and does not work in Firefox.
Most times it's possible to drop an item in exactly one place, sometimes it's not possible to drop it somewhere at all.
Unfortunateley this is a game breaker. ;)

Since Firefox is a modern browser supporting latest web features it must be an issue in code.
Tested in Firefox 59.

**Comment by tobihagemann** [comment]
Thank you for your bug report, @Fensterbank! Hm, I've just tried it again with Firefox 59.0.1 and I didn't have major issues. Well, I notice some weird lags that I don't have with other browsers but it's a minor issue here.

But I can imagine that there is a performance issue in my drag & drop code (which would explain my lags) that could make the game unplayable. I'll have a closer look at it.

**Comment by Fensterbank** [comment]
Okay, this is weird, since for me it's a quite breaking issue.
Should be reproduceable but on the other hand I'm wondering nobody mentioned it in the twitter posts so I'm afraid it only affects me…
 
I just made a screen record: https://wolke.bol.vin/s/XRTJChalFjJvs8x

**Comment by panmona** [comment]
I can't load the site where that screen recording lies.
Which platform are you testing on? @Fensterbank

**Comment by Fensterbank** [comment]
@maracuja-juice Eh, yes. Unfortunately my router died this night and the server is hosted in my living room. Very unfortunate timing… 🤔
My ISP fixed it, I configured the new Fritzbox and the site is back up and running.

I tested on Firefox 59.0.1 on Manjaro Linux.

**Comment by tobihagemann** [comment]
Thank you for the screen recording! I've improved the drag & drop performance (and it's less janky in Firefox, at least on my machine). It's still kind of laggy though and I know this could be improved even further. I didn't want to change too much because I noticed that some of my experiments didn't work out on mobile devices. 😕

Feel free to try out the new version and let me know if it works for you @Fensterbank.

**Comment by panmona** [comment]
@tobihagemann
Instead of reinventing the wheel with your drag and drop have you considered to use one of the popular libraries instead? / What are the reasons why you run your own? 

For example:
- https://github.com/bevacqua/dragula
- https://github.com/Shopify/draggable 
- https://github.com/RubaXa/Sortable
- https://github.com/marceljuenemann/angular-drag-and-drop-lists

**Comment by tobihagemann** [comment]
@maracuja-juice I actually did (well to be completely honest, just dragula from your list) and this gave me a lot of headache. I couldn't figure out how to use these libraries for my needs. Most of them are very good at sorting/reordering but they follow the following paradigm: "all elements can take any place in the collection."

This isn't exactly what I need for this game. Yes, there is sorting/reordering involved in the game but you can't have the words being placed "freely". Especially these rules apply:

1. You can't drag a word from the bottom to the top.
2. If you drag a new word from the top, you'll have "one more" word to deal with in the bottom collection.
3. Words at the bottom have a "fixed" position and they have to "stay" in the position during a drag. Except when the player decides to put a new word in its place.

I chose to implement this game with HTML5 Drag and Drop API because it seemed to be the easiest way at that time. But to be completely honest, I didn't try out every library. Especially `draggable` by Shopify looks extremely promising. I just need something that gives me as much control as possible.

**Comment by panmona** [comment]
@tobihagemann You seem to have chosen the better approach then.

**Comment by reppners** [comment]
If you ever refactor this you might want to check out https://github.com/reppners/ngx-drag-drop ;)
